name: Generate artifacts with the package of the extension for chrome and firefox

on: ["push", "pull_request"]

jobs:
  Generate-Artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout of the source code
        uses: actions/checkout@v5

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install dependancies
        run: npm ci

      - name: Check vulnerabilities
        run: npm audit

      - name: Lint code
        run: npm run lint:check

      - name: Generate Chrome Build
        run: npm run build

      - name: Generate Firefox Build
        run: npm run build:firefox

      - name: ls files
        run: ls -la

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: artifacts
      #     path: .output/

      - name: Upload Chrome Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chromeArtifact
          path: .output/chrome-mv3/

      - name: Upload Firefox Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firefoxArtifact
          path: .output/firefox-mv2/
